name: Discord Notification

on:
  push:
    branches:
      - main 

jobs:
  discord_notification:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Send notification to Discord
      uses: appleboy/discord-action@master
      with:
        webhook_id: 1141503061278326825
        webhook_token: dJn6sm9SlTSxGuGUqhKRrRONCPHdB3l4jSvv0Z03nwa50JfFnzR8qunkvqa52Ju_mf8K
        text: 'Novo commit na branch: ${{ github.ref }} por ${{ github.actor }}.'
